"""Full-server backup: bundle every configured mikromon data file (config,
auth/devices/billing/metrics/push-log SQLite DBs, the tunnel-IP registry,
alert dedup state) into one archive, so a superadmin can move the whole
install to a new server. Backups are created into a persistent directory
(so they can be listed and re-downloaded later, not just streamed once) and
restored either from that list or from an uploaded file.

NOT included — these live outside mikromon's own data files and need to be
carried over separately when moving hosts:
  * The hub's WireGuard identity (/etc/wireguard/ — private key, wg0.conf,
    wg-peers.conf). It's root-owned and outside the app's data directory, and
    every already-provisioned router has this hub's PUBLIC key configured as
    its dial-home peer — replacing it breaks every router's tunnel until
    they're re-provisioned. Copy /etc/wireguard/ from the old host to the new
    one (as root) so existing routers keep dialing home without changes.
  * nginx/systemd config and the TLS certificate — regenerated by
    deploy/install.sh on the new host.

All scratch/temp files are created INSIDE the backups directory rather than
the system temp dir — under the hardened systemd unit (ProtectSystem=strict)
only paths under ReadWritePaths= (/opt/mikromon) are guaranteed writable, and
the backups directory always lives there.
"""
from __future__ import annotations

import io
import os
import re
import sqlite3
import tarfile
import time

_NAME_RE = re.compile(r"^[A-Za-z0-9_.-]+\.tar\.gz$")


def backups_dir_for(*, config_path=None, devices_db=None) -> str:
    """Where created backups live and where restores are read from. Anchored
    next to config.yaml (falling back to devices.db's directory, then cwd) so
    it's always inside the app's writable data directory."""
    base = os.path.dirname(config_path or "") or os.path.dirname(devices_db or "")
    return os.path.join(base or ".", "backups-server")


def backup_paths(*, config_path=None, auth_db=None, devices_db=None,
                 metrics_db=None, push_log_db=None, billing_db=None,
                 state_file=None, access_grants_file=None) -> dict:
    """Map archive-member-name -> configured source path. Anything not
    configured (None/empty) is simply omitted from the mapping."""
    paths: dict = {}
    if config_path:
        paths["config.yaml"] = config_path
    if auth_db:
        paths["auth.db"] = auth_db
    if devices_db:
        paths["devices.db"] = devices_db
        # hub.json (tunnel-IP allocation registry) lives alongside devices.db.
        paths["hub.json"] = os.path.join(
            os.path.dirname(devices_db) or ".", "hub.json")
    if metrics_db:
        paths["metrics.db"] = metrics_db
    if push_log_db:
        paths["push_log.db"] = push_log_db
    if billing_db:
        paths["billing.db"] = billing_db
    if state_file:
        paths["state.json"] = state_file
    if access_grants_file:
        paths["access-grants.json"] = access_grants_file
    return paths


def _add_sqlite_snapshot(tar: tarfile.TarFile, arcname: str, path: str,
                         mtime: float, tmp_dir: str) -> None:
    """Add a SQLite DB using sqlite3's own backup API rather than a raw file
    copy. These DBs run in WAL mode and stay open under the live server, so a
    plain copy could catch a write mid-flight or miss pages still sitting in
    the -wal file; backup() produces a consistent, fully-checkpointed
    snapshot regardless."""
    tmp_path = os.path.join(tmp_dir, f".snapshot-{os.getpid()}-{time.time_ns()}.db")
    try:
        src = sqlite3.connect(path)
        try:
            dst = sqlite3.connect(tmp_path)
            try:
                src.backup(dst)
            finally:
                dst.close()
        finally:
            src.close()
        info = tarfile.TarInfo(arcname)
        info.size = os.path.getsize(tmp_path)
        info.mtime = mtime
        with open(tmp_path, "rb") as fh:
            tar.addfile(info, fh)
    finally:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)


def build_archive_to_file(paths: dict, out_path: str) -> list:
    """Tar+gzip every existing file in `paths` (archive name -> source path)
    straight to `out_path` on disk. Missing files (e.g. a DB feature that
    was never enabled) are silently skipped rather than failing the whole
    backup.

    Returns a list of (arcname, error) for files that EXIST but couldn't be
    read (e.g. access-grants.json, whose ownership legitimately flips
    between the web service and the root-run access-reload timer that prunes
    it every minute — whichever wrote it last is the only one that can read
    its 0600 permissions). One unreadable, low-value file must not fail the
    whole backup — the caller can surface these as a warning.

    Writes to disk rather than building the archive in memory: metrics.db
    can grow large, and holding a full in-memory copy (on top of the SQLite
    snapshot machinery and the HTTP response buffer) risks the server
    process getting OOM-killed mid-request on a small VPS. Scratch files for
    the SQLite snapshots are created next to `out_path` (see module docstring
    for why — it must be a directory the sandboxed service can actually
    write to)."""
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    now = time.time()
    tmp_dir = os.path.dirname(out_path) or "."
    skipped = []
    with tarfile.open(out_path, mode="w:gz") as tar:
        for arcname, path in paths.items():
            if not path or not os.path.isfile(path):
                continue
            try:
                if path.endswith(".db"):
                    _add_sqlite_snapshot(tar, arcname, path, now, tmp_dir)
                else:
                    tar.add(path, arcname=arcname)
            except Exception as exc:  # noqa: BLE001 — one bad file must not sink the backup
                skipped.append((arcname, str(exc)))
    return skipped


def build_archive(paths: dict, tmp_dir: str = ".") -> bytes:
    """Convenience wrapper returning the archive as bytes — fine for tests
    and small archives. Prefer build_archive_to_file for anything that might
    be large (see its docstring)."""
    tmp_path = os.path.join(tmp_dir, f".build-{os.getpid()}-{time.time_ns()}.tar.gz")
    try:
        build_archive_to_file(paths, tmp_path)
        with open(tmp_path, "rb") as fh:
            return fh.read()
    finally:
        if os.path.exists(tmp_path):
            os.unlink(tmp_path)


def backup_filename(prefix: str = "mikromon-backup") -> str:
    return f"{prefix}-{time.strftime('%Y%m%d-%H%M%S')}.tar.gz"


def is_safe_backup_name(name: str) -> bool:
    """True if `name` is a bare filename (no path separators / traversal)
    ending in .tar.gz — the only kind accepted for download/delete/restore
    so a crafted name can never escape the backups directory."""
    return bool(name) and _NAME_RE.match(name) is not None and "/" not in name


def list_backups(backups_dir: str) -> list:
    """Existing backups in `backups_dir`, newest first. Empty list if the
    directory doesn't exist yet (no backup has been created)."""
    if not os.path.isdir(backups_dir):
        return []
    out = []
    for name in os.listdir(backups_dir):
        if not is_safe_backup_name(name):
            continue
        path = os.path.join(backups_dir, name)
        if os.path.isfile(path):
            st = os.stat(path)
            out.append({"name": name, "path": path, "size": st.st_size,
                       "mtime": st.st_mtime})
    out.sort(key=lambda b: b["mtime"], reverse=True)
    return out


def restore_archive_from_path(archive_path: str, paths: dict) -> list:
    """Like restore_archive, but reads the archive straight from disk instead
    of requiring the whole thing in memory first — used for restoring an
    on-server backup, which could be large."""
    with tarfile.open(archive_path, mode="r:gz") as tar:
        return _restore_from_tar(tar, paths)


def restore_archive(data: bytes, paths: dict) -> list:
    """Extract each member of a backup archive back to its configured
    destination (the same archive-name -> path mapping `backup_paths`
    builds). Members not present in `paths` (or vice versa) are ignored —
    this only ever writes files this install is actually configured to use.
    Used for restoring an uploaded file, whose bytes are already in memory
    as part of the request body. Run this with the service stopped — it
    does not coordinate with a live process holding these files open."""
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as tar:
        return _restore_from_tar(tar, paths)


def _restore_from_tar(tar: tarfile.TarFile, paths: dict) -> list:
    """Each file is written to a `.restoring` temp name next to its
    destination and atomically renamed into place, so a crash mid-restore
    never leaves a half-written DB where a real one used to be."""
    written = []
    members = set(tar.getnames())
    for arcname, dest in paths.items():
        if arcname not in members or not dest:
            continue
        member = tar.extractfile(arcname)
        os.makedirs(os.path.dirname(dest) or ".", exist_ok=True)
        tmp = f"{dest}.restoring"
        with open(tmp, "wb") as fh:
            fh.write(member.read())
        os.replace(tmp, dest)
        if dest.endswith(".db"):
            # Drop any pre-existing WAL/SHM sidecar files for the OLD version
            # of this database. SQLite validates a -wal file against the main
            # file before trusting it, so a mismatched one is normally just
            # ignored — but a stale sidecar left with different ownership
            # (e.g. from a process that touched the old file as a different
            # user) can still block the service from opening its replacement
            # cleanly. A freshly-restored DB doesn't need them anyway.
            for suffix in ("-wal", "-shm"):
                sidecar = dest + suffix
                if os.path.exists(sidecar):
                    os.unlink(sidecar)
        written.append(dest)
    return written
