"""Full-server backup: bundle every configured mikromon data file (config,
auth/devices/billing/metrics/push-log SQLite DBs, the tunnel-IP registry,
alert dedup state) into one downloadable archive, so a superadmin can move
the whole install to a new server.

NOT included — these live outside mikromon's own data files and need to be
carried over separately when moving hosts:
  * The hub's WireGuard identity (/etc/wireguard/ — private key, wg0.conf,
    wg-peers.conf). It's root-owned and outside the app's data directory, and
    every already-provisioned router has this hub's PUBLIC key configured as
    its dial-home peer — replacing it breaks every router's tunnel until
    they're re-provisioned. Copy /etc/wireguard/ from the old host to the new
    one (as root) so existing routers keep dialing home without changes.
  * nginx/systemd config and the TLS certificate — regenerated by
    deploy/install.sh on the new host.
"""
from __future__ import annotations

import io
import os
import sqlite3
import tarfile
import tempfile
import time


def backup_paths(*, config_path=None, auth_db=None, devices_db=None,
                 metrics_db=None, push_log_db=None, billing_db=None,
                 state_file=None, access_grants_file=None) -> dict:
    """Map archive-member-name -> configured source path. Anything not
    configured (None/empty) is simply omitted from the mapping."""
    paths: dict = {}
    if config_path:
        paths["config.yaml"] = config_path
    if auth_db:
        paths["auth.db"] = auth_db
    if devices_db:
        paths["devices.db"] = devices_db
        # hub.json (tunnel-IP allocation registry) lives alongside devices.db.
        paths["hub.json"] = os.path.join(
            os.path.dirname(devices_db) or ".", "hub.json")
    if metrics_db:
        paths["metrics.db"] = metrics_db
    if push_log_db:
        paths["push_log.db"] = push_log_db
    if billing_db:
        paths["billing.db"] = billing_db
    if state_file:
        paths["state.json"] = state_file
    if access_grants_file:
        paths["access-grants.json"] = access_grants_file
    return paths


def _add_sqlite_snapshot(tar: tarfile.TarFile, arcname: str, path: str,
                         mtime: float) -> None:
    """Add a SQLite DB using sqlite3's own backup API rather than a raw file
    copy. These DBs run in WAL mode and stay open under the live server, so a
    plain copy could catch a write mid-flight or miss pages still sitting in
    the -wal file; backup() produces a consistent, fully-checkpointed
    snapshot regardless."""
    fd, tmp_path = tempfile.mkstemp(suffix=".db")
    os.close(fd)
    try:
        src = sqlite3.connect(path)
        try:
            dst = sqlite3.connect(tmp_path)
            try:
                src.backup(dst)
            finally:
                dst.close()
        finally:
            src.close()
        info = tarfile.TarInfo(arcname)
        info.size = os.path.getsize(tmp_path)
        info.mtime = mtime
        with open(tmp_path, "rb") as fh:
            tar.addfile(info, fh)
    finally:
        os.unlink(tmp_path)


def build_archive_to_file(paths: dict, out_path: str) -> None:
    """Tar+gzip every existing file in `paths` (archive name -> source path)
    straight to `out_path` on disk. Missing files (e.g. a DB feature that
    was never enabled) are silently skipped rather than failing the whole
    backup.

    Writes to disk rather than building the archive in memory: metrics.db
    can grow large, and holding a full in-memory copy (on top of the SQLite
    snapshot machinery and the HTTP response buffer) risks the server
    process getting OOM-killed mid-request on a small VPS — exactly the
    kind of failure a backup feature must not cause."""
    now = time.time()
    with tarfile.open(out_path, mode="w:gz") as tar:
        for arcname, path in paths.items():
            if not path or not os.path.isfile(path):
                continue
            if path.endswith(".db"):
                _add_sqlite_snapshot(tar, arcname, path, now)
            else:
                tar.add(path, arcname=arcname)


def build_archive(paths: dict) -> bytes:
    """Convenience wrapper returning the archive as bytes — fine for tests
    and small archives. Prefer build_archive_to_file for anything that might
    be large (see its docstring); the web download handler and the CLI's
    backup-server command both use it directly."""
    fd, tmp_path = tempfile.mkstemp(suffix=".tar.gz")
    os.close(fd)
    try:
        build_archive_to_file(paths, tmp_path)
        with open(tmp_path, "rb") as fh:
            return fh.read()
    finally:
        os.unlink(tmp_path)


def backup_filename(prefix: str = "mikromon-backup") -> str:
    return f"{prefix}-{time.strftime('%Y%m%d-%H%M%S')}.tar.gz"


def restore_archive(data: bytes, paths: dict) -> list:
    """Extract each member of a backup archive back to its configured
    destination (the same archive-name -> path mapping `backup_paths`
    builds). Members not present in `paths` (or vice versa) are ignored —
    this only ever writes files this install is actually configured to use.

    Each file is written to a `.restoring` temp name next to its destination
    and atomically renamed into place, so a crash mid-restore never leaves a
    half-written DB where a real one used to be. Run this with the service
    stopped — it does not coordinate with a live process holding these files
    open."""
    written = []
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as tar:
        members = set(tar.getnames())
        for arcname, dest in paths.items():
            if arcname not in members or not dest:
                continue
            member = tar.extractfile(arcname)
            os.makedirs(os.path.dirname(dest) or ".", exist_ok=True)
            tmp = f"{dest}.restoring"
            with open(tmp, "wb") as fh:
                fh.write(member.read())
            os.replace(tmp, dest)
            written.append(dest)
    return written
